---

name: "umccr_workflow_test"
pack: "arteria"
description: "Runs a simplified UMCCR workflow for testing."
enabled: false

trigger:
    type: "arteria.incoming_ready"

action:
    ref: "arteria.umccr_test"
    parameters:
        bcl2fastq_host: "bcl2fastq_ws"
        bcl2fastq_dest_path: "/opt/runfolder"
        runfolder: "{{ trigger.runfolder }}"
        runfolder_name: "{{ trigger.runfolder_name }}"
        runfolder_host: "runfolder_ws"
